### ISSUE TITLE
accept: out of file descriptors, backing off for xxx ms: Too many open file

### ISSUE THREAD

**Issue by eminarcissus** [darkk/redsocks#36]
I used this program as a transparent proxy gateway.
In most time it works like a charm.

But seems it quite often get into out of file descriptor problem. It both happens on mipsel openwrt and x86 debian box.

here is the log when issue appears.
http://pastebin.com/5ZmXRZQm

And here is my lsof snapshot when this problem happens:
http://pastebin.com/0UuWeguF

Seems have something to do with not cleanly close the connection?

**Comment by konfiot** [comment]
Has there been any progress on this issue ? I'm Stumbling on the same problem...

**Comment by comm1x** [comment]
@konfiot Yes, migrate to proxychains :)

**Comment by darkk** [comment]
@konfiot, @comm1x there were some bugs fixed in 0.5 that triggered socket leak.

Maybe that's not all the possible bugs triggering file descriptors leaks in this 10-year-old code, but it's all the bugs I managed to find while stess-testing it on OpenWRT as a part of another project :-)

@semigodking also did awesome [fork named redsocks2](https://github.com/semigodking/redsocks) that is done with censorship circumvention in mind, it may be more well-maintained as the developer is actually using the software. I'll unlikely have time and courage to integrate all of the patches from redsocks2 to redsocks as it's quite major rewrite.

I'm closing this bug as connection pressure handler was significantly rewritten, please, open another one if you observe alike behavior while using redsocks-0.5.
